---
apiVersion: v1
kind: Service
metadata:
  name: 'website'
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 80
  selector:
    name: 'website'
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: 'website'
  namespace: default
  labels:
    name: 'website'
spec:
  replicas: 1
  selector:
    matchLabels:
      name: 'website'
  template:
    metadata:
      labels:
        name: 'website'
    spec:
      containers:
        - name: 'worker'
          image: gcr.io/PROJECT_ID/IMAGE:TAG
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
          envFrom:
            - secretRef:
                name: website
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: website-https
spec:
  routes:
  - kind: Rule
    match: Host(`catacomb.ai`)
    services:
    - kind: Service
      name: website
      port: 80
  tls:
    secretName: website-cert
    domains:
    - main: catacomb.ai
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: website-http
spec:
  routes:
  - kind: Rule
    match: Host(`catacomb.ai`)
    services:
    - kind: Service
      name: website
      port: 80
    middlewares:
    - name: https-redirect
---
apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: website-cert
spec:
  secretName: website-cert
  dnsNames:
    - catacomb.ai
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt
